backend:
  name: git-gateway
  branch: master
media_folder: "images" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Links"
        name: "links"
        file: "data/links.json"
        fields:
          - label: "Link"
            name: "link"
            widget: "list"
            allow_add: true
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
                  